### PR TITLE
Auri: Release request (v2.0.0-next.0)

### PR DESCRIPTION
**Pull request by pilcrowonpaper**
## Major changes
- Breaking: Update `OAuth2RequestError`
- Breaking: Update `OAuth2Client`
- Breaking: Remove `oslo/password`
- Breaking: Remove `oslo/request`
- Breaking: Update `createJWT()` and `validateJWT()` parameters
- Breaking: Replace `oslo/webauthn` with `oslo/passkey`
- Breaking: Rename `createDate()` to `addToDate()`
- Breaking: Remove `encodeBase32()`, `decodeBase32()`, `encodeBase64()`, `decodeBase64()`, `encodeBase64url()`, and `decodeBase64url()`,
- Breaking: Functions only accept `Uint8Array` instead of `TypedArray | ArrayBuffer`
## Minor changes
- Feat: Add `SigningAlgorithm` interface
- Feat: Add `createJWTHeader()` and `createJWTPayload()`
- Feat: `sha1()`, `sha256()`, `sha384()`, and `sha512()` is synchronous
- Feat: Add `TokenRevocationClient`, `TokenRevocationRetryError`, and `TokenRevocationRequestContext`
- Feat: Add `oslo/binary`
- Feat: Add `OAuth2RequestError`
- Feat: Add `OAuth2RequestContext`, `AccessTokenRequestContext`, `RefreshTokenRequestContext`, and `OAuth2Request`
- Feat: Add `generateRandomBoolean()`

### CODE REVIEW

**Comment by Wundero** [comment]
Out of curiosity, what are the reasons for dropping `oslo/password`? I saw one reason being the poor nextjs support (in your comment [here](https://github.com/vercel/next.js/issues/63850#issuecomment-2088282499)), but want to know what other reasons you have.

**Comment by pilcrowonpaper** [comment]
@Wundero 
I guess fundamentally, it was kinda dumb to have Node-only modules in a runtime agnostic library

**Comment by rwieruch** [comment]
Will this result in a major Lucia v4? And is there any timeline on dropping Oslo? Just double checking here for a course release :) Thanks for keeping up with everything @pilcrowOnPaper !

**Comment by pilcrowonpaper** [comment]
No major updates, since password hashing isn't part of Lucia. I might push the branch early this month, but you should be fine staying in Oslo v1 for quite a while

**Pull request closed without merging**
